/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 computer.gltf 
Author: NotAGanesh (https://sketchfab.com/kgytofficial2022)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/retro-computer-low-poly-blockbench-e6f953bd52054190a23e55884cd0537a
Title: Retro Computer | Low-Poly | BlockBench
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/computer.gltf')
  const computerRef = useRef();

  useFrame((state, delta) => {
    computerRef.current.rotation.y -= 0.02
  })

  return (
    <group position={[0, -2.5, 0]} ref={computerRef} {...props} dispose={null} scale={7} >
      <mesh geometry={nodes.Object_6.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.material_0} rotation={[0, 0, 0.14]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.material_0} rotation={[0, 0, -0.14]} />
    </group>
  )
}

useGLTF.preload('/computer.gltf')
